/* Auto-generated by psvita-toolkit -- see generated_jni_table.h */
#include <falso_jni/FalsoJNI_Impl.h>
#include "generated_jni_table.h"

// ---- com.amazon.ags.jni.AGSJniHandler ----
void stub_AGSJniHandler_initializeJni_0(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.amazon.ags.jni.AGSJniHandler.initializeJni(LAmazonGamesClient;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_AGSJniHandler_loadLibrary_1(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.amazon.ags.jni.AGSJniHandler.loadLibrary()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_AGSJniHandler_isLibraryLoaded_2(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.amazon.ags.jni.AGSJniHandler.isLibraryLoaded()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

// ---- com.chartboost.sdk.Libraries.NaCl ----
jbyteArray stub_NaCl_a_3(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.chartboost.sdk.Libraries.NaCl.a()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

// ---- com.crittercism.app.CrittercismNDK ----
jboolean stub_CrittercismNDK_installLib_4(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.crittercism.app.CrittercismNDK.installLib(LContext;)Z called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

void stub_CrittercismNDK_installNdkLib_5(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.crittercism.app.CrittercismNDK.installNdkLib(LContext;Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);
}

// ---- com.tatem.billing.Billing ----
jobject stub_Billing_Billing_6(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.billing.Billing.Billing(LContext;Z)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jboolean arg1 = (jboolean) va_arg(args, int);
    return NULL;
}

void stub_Billing_addObserver_7(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.billing.Billing.addObserver(LBillingObserver;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_Billing_removeObserver_8(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.billing.Billing.removeObserver(LBillingObserver;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_Billing_destroy_9(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.billing.Billing.destroy()V called -- fill in from the real Java impl (jadx).");
}

void stub_Billing_onActivityResult_10(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.billing.Billing.onActivityResult(IILIntent;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jobject arg2 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_Billing_notifyItemPurhcased_11(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.billing.Billing.notifyItemPurhcased(Ljava/lang/String;Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
}

void stub_Billing_notifyPurchaseRestored_12(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.billing.Billing.notifyPurchaseRestored(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_Billing_notifyPurchaseCanceled_13(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.billing.Billing.notifyPurchaseCanceled()V called -- fill in from the real Java impl (jadx).");
}

void stub_Billing_notifyPurchaseFailed_14(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.billing.Billing.notifyPurchaseFailed(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_Billing_log_15(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.billing.Billing.log(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

// ---- com.tatem.iceage.IceAgeAndroid ----
jobject stub_IceAgeAndroid_getInstance_16(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.getInstance()LIceAgeAndroid; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_IceAgeAndroid_getGameHelper_17(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.getGameHelper()LGameHelper; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_IceAgeAndroid_onCreate_18(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.onCreate(LBundle;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_IceAgeAndroid_onStart_19(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.onStart()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_onStop_20(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.onStop()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_onActivityResult_21(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.onActivityResult(IILIntent;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jobject arg2 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

jobject stub_IceAgeAndroid_getApiClient_22(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.getApiClient()LGoogleApiClient; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jboolean stub_IceAgeAndroid_isSignedIn_23(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.isSignedIn()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_IceAgeAndroid_beginUserInitiatedSignIn_24(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.beginUserInitiatedSignIn()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_beginUserInitiatedSignIn_25(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.beginUserInitiatedSignIn(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_IceAgeAndroid_signOut_26(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.signOut()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_showAlert_27(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.showAlert(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_IceAgeAndroid_showAlert_28(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.showAlert(Ljava/lang/String;Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
}

void stub_IceAgeAndroid_enableDebugLog_29(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.enableDebugLog(Z)V called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
}

void stub_IceAgeAndroid_enableDebugLog_30(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.enableDebugLog(ZLjava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);
}

jobject stub_IceAgeAndroid_getInvitationId_31(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.getInvitationId()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_IceAgeAndroid_reconnectClient_32(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.reconnectClient()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_IceAgeAndroid_hasSignInError_33(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.hasSignInError()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

jobject stub_IceAgeAndroid_getSignInError_34(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.getSignInError()LGameHelper.SignInFailureReason; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_IceAgeAndroid_getSignInTextError_35(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.getSignInTextError(I)Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return NULL;
}

void stub_IceAgeAndroid_onWindowFocusChanged_36(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.onWindowFocusChanged(Z)V called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
}

void stub_IceAgeAndroid_finish_37(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.finish()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_IceAgeAndroid_onKeyDown_38(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.onKeyDown(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

void stub_IceAgeAndroid_onBackPressed_39(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.onBackPressed()V called -- fill in from the real Java impl (jadx).");
}

jobject stub_IceAgeAndroid_onCreateDialog_40(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.onCreateDialog(I)LDialog; called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return NULL;
}

void stub_IceAgeAndroid_postDownloadInit_41(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.postDownloadInit()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_checkBundles_42(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.checkBundles()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_continueCreating_43(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.continueCreating()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_loadThanksGivingMode_44(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.loadThanksGivingMode()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_createGallery_45(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.createGallery()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_createSocialButton_46(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.createSocialButton()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_createHotAppButton_47(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.createHotAppButton()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_showLoadingDialog_48(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.showLoadingDialog(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_IceAgeAndroid_hideLoadingDialog_49(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.hideLoadingDialog()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_showAlertDialog_50(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.showAlertDialog(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_IceAgeAndroid_showSplash_51(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.showSplash()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_onLoadingCompleted_52(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.onLoadingCompleted()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_init_53(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.init()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_initViews_54(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.initViews()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_setActivityOptions_55(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.setActivityOptions()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_onPause_56(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.onPause()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_onResume_57(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.onResume()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_onDestroy_58(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.onDestroy()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_showGallery_59(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.showGallery()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_hideGallery_60(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.hideGallery()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_createHelpView_61(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.createHelpView()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_showTutorial_62(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.showTutorial()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_hideTutorial_63(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.hideTutorial()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_showInAppInfo_64(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.showInAppInfo()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_hideInAppInfo_65(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.hideInAppInfo()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_setTutorialFile_66(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.setTutorialFile(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_IceAgeAndroid_putFrameOnPhoto_67(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.putFrameOnPhoto(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_IceAgeAndroid_showSignInDialog_68(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.showSignInDialog(ILDialogInterface.OnClickListener;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_IceAgeAndroid_showSignInProposeAtFirst_69(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.showSignInProposeAtFirst()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_showSignInPropose_70(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.showSignInPropose(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_IceAgeAndroid_showSignInPropose_71(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.showSignInPropose(II)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_IceAgeAndroid_showSocialButton_72(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.showSocialButton()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_hideSocialButton_73(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.hideSocialButton()V called -- fill in from the real Java impl (jadx).");
}

jobject stub_IceAgeAndroid_getCurrentLanguage_74(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.getCurrentLanguage()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_IceAgeAndroid_checkLanguageChange_75(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.checkLanguageChange()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_showSpinner_76(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.showSpinner()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_hideSpinner_77(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.hideSpinner()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_isInGameMode_78(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.isInGameMode()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_isInMenuMode_79(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.isInMenuMode()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_createInAppInfoView_80(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.createInAppInfoView()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_processPurchaseForGoogle_81(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.processPurchaseForGoogle(LBillingReport;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_IceAgeAndroid_initAmazonBilling_82(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.initAmazonBilling()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_processPurchase_83(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.processPurchase(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_IceAgeAndroid_purchaseItem_84(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.purchaseItem(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

jobject stub_IceAgeAndroid_processSnapshotOpenResult_85(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.processSnapshotOpenResult(LSnapshots.OpenSnapshotResult;I)LSnapshot; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
    return NULL;
}

void stub_IceAgeAndroid_resolveSnapshotConflict_86(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.resolveSnapshotConflict(LSnapshots.OpenSnapshotResult;I)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
}

void stub_IceAgeAndroid_saveSnapshot_87(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.saveSnapshot()V called -- fill in from the real Java impl (jadx).");
}

jobject stub_IceAgeAndroid_writeSnapshot_88(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.writeSnapshot(LSnapshot;)Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_IceAgeAndroid_loadFromSnapshot_89(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.loadFromSnapshot()V called -- fill in from the real Java impl (jadx).");
}

void stub_IceAgeAndroid_setLoadingBalance_90(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.setLoadingBalance()V called -- fill in from the real Java impl (jadx).");
}

jobject stub_IceAgeAndroid_getSnapshot_91(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.getSnapshot()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_IceAgeAndroid_setSnapshot_92(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeAndroid.setSnapshot(LSnapshot;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

// ---- com.tatem.iceage.IceAgeGLSurface ----
jobject stub_IceAgeGLSurface_IceAgeGLSurface_93(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeGLSurface.IceAgeGLSurface(LContext;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

jobject stub_IceAgeGLSurface_IceAgeGLSurface_94(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeGLSurface.IceAgeGLSurface(LContext;LAttributeSet;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

jboolean stub_IceAgeGLSurface_onTouchEvent_95(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeGLSurface.onTouchEvent(LMotionEvent;)Z called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

void stub_IceAgeGLSurface_dumpEvent_96(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeGLSurface.dumpEvent(LMotionEvent;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

// ---- com.tatem.iceage.IceAgeRenderer ----
jobject stub_IceAgeRenderer_IceAgeRenderer_97(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeRenderer.IceAgeRenderer(LContext;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_IceAgeRenderer_onDrawFrame_98(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeRenderer.onDrawFrame(LGL10;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_IceAgeRenderer_onSurfaceChanged_99(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeRenderer.onSurfaceChanged(LGL10;II)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
}

void stub_IceAgeRenderer_onSurfaceCreated_100(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.IceAgeRenderer.onSurfaceCreated(LGL10;LEGLConfig;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

// ---- com.tatem.iceage.utils.FacebookWrapper ----
jobject stub_FacebookWrapper_FacebookWrapper_101(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.FacebookWrapper.FacebookWrapper()Lpublic; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_FacebookWrapper_onStart_102(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.FacebookWrapper.onStart()V called -- fill in from the real Java impl (jadx).");
}

void stub_FacebookWrapper_onStop_103(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.FacebookWrapper.onStop()V called -- fill in from the real Java impl (jadx).");
}

void stub_FacebookWrapper_logIn_104(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.FacebookWrapper.logIn()V called -- fill in from the real Java impl (jadx).");
}

void stub_FacebookWrapper_logOut_105(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.FacebookWrapper.logOut()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_FacebookWrapper_isLoggedIn_106(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.FacebookWrapper.isLoggedIn()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_FacebookWrapper_publishFeed_107(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.FacebookWrapper.publishFeed(Ljava/lang/String;Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
}

void stub_FacebookWrapper_getUserName_108(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.FacebookWrapper.getUserName()V called -- fill in from the real Java impl (jadx).");
}

void stub_FacebookWrapper_onClickLogin_109(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.FacebookWrapper.onClickLogin()V called -- fill in from the real Java impl (jadx).");
}

void stub_FacebookWrapper_onClickLogout_110(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.FacebookWrapper.onClickLogout()V called -- fill in from the real Java impl (jadx).");
}

void stub_FacebookWrapper_showDialogWithoutNotificationBar_111(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.FacebookWrapper.showDialogWithoutNotificationBar(Ljava/lang/String;LBundle;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

// ---- com.tatem.iceage.utils.FyberManager ----
jobject stub_FyberManager_FyberManager_112(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.FyberManager.FyberManager(LActivity;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_FyberManager_startFyber_113(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.FyberManager.startFyber()V called -- fill in from the real Java impl (jadx).");
}

jobject stub_FyberManager_getButtonText_114(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.FyberManager.getButtonText(I)Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return NULL;
}

void stub_FyberManager_showAd_115(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.FyberManager.showAd()V called -- fill in from the real Java impl (jadx).");
}

void stub_FyberManager_isFyberAdsAvaliable_116(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.FyberManager.isFyberAdsAvaliable(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_FyberManager_isReviveAvailable_117(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.FyberManager.isReviveAvailable()V called -- fill in from the real Java impl (jadx).");
}

void stub_FyberManager_onActivityResult_118(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.FyberManager.onActivityResult(IILIntent;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jobject arg2 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

// ---- com.tatem.iceage.utils.InternetUtils ----
jobject stub_InternetUtils_InternetUtils_119(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.InternetUtils()Lpublic; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_InternetUtils_onConnectSuccess_120(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.onConnectSuccess()V called -- fill in from the real Java impl (jadx).");
}

void stub_InternetUtils_onConnectFails_121(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.onConnectFails()V called -- fill in from the real Java impl (jadx).");
}

jobject stub_InternetUtils_getInstance_122(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.getInstance()LInternetUtils; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_InternetUtils_onPause_123(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.onPause()V called -- fill in from the real Java impl (jadx).");
}

void stub_InternetUtils_onResume_124(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.onResume()V called -- fill in from the real Java impl (jadx).");
}

void stub_InternetUtils_onDestroy_125(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.onDestroy()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_InternetUtils_isOnline_126(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.isOnline(Z)Z called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
    return JNI_FALSE;
}

void stub_InternetUtils_showOfflineDialog_127(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.showOfflineDialog()V called -- fill in from the real Java impl (jadx).");
}

void stub_InternetUtils_openHotAppBanner_128(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.openHotAppBanner(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

jboolean stub_InternetUtils_getOfferwalShowed_129(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.getOfferwalShowed()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_InternetUtils_setOfferWallShowed_130(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.setOfferWallShowed()V called -- fill in from the real Java impl (jadx).");
}

void stub_InternetUtils_openAfterGameStarts_131(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.openAfterGameStarts()V called -- fill in from the real Java impl (jadx).");
}

void stub_InternetUtils_openMoreGames_132(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.openMoreGames()V called -- fill in from the real Java impl (jadx).");
}

void stub_InternetUtils_openTapJoyOffers_133(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.openTapJoyOffers(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_InternetUtils_openMarketAtPackage_134(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.openMarketAtPackage(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_InternetUtils_LoadAd_135(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.LoadAd()V called -- fill in from the real Java impl (jadx).");
}

void stub_InternetUtils_createAMZNAd_136(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.createAMZNAd()V called -- fill in from the real Java impl (jadx).");
}

void stub_InternetUtils_removeAMZNAd_137(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.removeAMZNAd()V called -- fill in from the real Java impl (jadx).");
}

void stub_InternetUtils_showAMZNAd_138(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.showAMZNAd()V called -- fill in from the real Java impl (jadx).");
}

void stub_InternetUtils_onAdCollapsed_139(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.onAdCollapsed(LAdLayout;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_InternetUtils_onAdFailedToLoad_140(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.onAdFailedToLoad(LAdLayout;LAdError;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_InternetUtils_onAdLoaded_141(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.onAdLoaded(LAdLayout;LAdProperties;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_InternetUtils_onAdExpanded_142(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.onAdExpanded(LAdLayout;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_InternetUtils_downloadPromoteJSON_143(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.downloadPromoteJSON()V called -- fill in from the real Java impl (jadx).");
}

jobject stub_InternetUtils_HTTPGetCall_144(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.InternetUtils.HTTPGetCall(Ljava/lang/String;)Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return NULL;
}

// ---- com.tatem.iceage.utils.MoPubManager ----
jobject stub_MoPubManager_MoPubManager_145(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.MoPubManager.MoPubManager(LActivity;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_MoPubManager_onCreate_146(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.MoPubManager.onCreate()V called -- fill in from the real Java impl (jadx).");
}

void stub_MoPubManager_onDestroy_147(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.MoPubManager.onDestroy()V called -- fill in from the real Java impl (jadx).");
}

void stub_MoPubManager_showAd_148(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.MoPubManager.showAd(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

jobject stub_MoPubManager_getNeedfulId_149(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.MoPubManager.getNeedfulId(I)Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return NULL;
}

// ---- com.tatem.iceage.utils.SocialUtils ----
jobject stub_SocialUtils_SocialUtils_150(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.SocialUtils.SocialUtils()Lpublic; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_SocialUtils_getInstance_151(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.SocialUtils.getInstance()LSocialUtils; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_SocialUtils_onResume_152(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.SocialUtils.onResume()V called -- fill in from the real Java impl (jadx).");
}

void stub_SocialUtils_onPause_153(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.SocialUtils.onPause()V called -- fill in from the real Java impl (jadx).");
}

void stub_SocialUtils_initAchievements_154(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.SocialUtils.initAchievements()V called -- fill in from the real Java impl (jadx).");
}

void stub_SocialUtils_synchronizeGameData_155(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.SocialUtils.synchronizeGameData(Z)V called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
}

void stub_SocialUtils_syncProgress_156(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.SocialUtils.syncProgress()V called -- fill in from the real Java impl (jadx).");
}

void stub_SocialUtils_initSocial_157(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.SocialUtils.initSocial()V called -- fill in from the real Java impl (jadx).");
}

void stub_SocialUtils_setAchievementsIDs_158(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.SocialUtils.setAchievementsIDs()V called -- fill in from the real Java impl (jadx).");
}

void stub_SocialUtils_openAchievements_159(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.SocialUtils.openAchievements(LGoogleApiClient;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_SocialUtils_openDashboard_160(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.SocialUtils.openDashboard()V called -- fill in from the real Java impl (jadx).");
}

void stub_SocialUtils_unlockAchievement_161(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.SocialUtils.unlockAchievement(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_SocialUtils_SendFlurryEvent_162(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.SocialUtils.SendFlurryEvent(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_SocialUtils_sendGAEvent_163(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.SocialUtils.sendGAEvent(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;J)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
    jobject arg2 = (jobject) va_arg(args, jobject);
    jlong arg3 = (jlong) va_arg(args, jlong);
}

void stub_SocialUtils_sendGAEvent_164(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.SocialUtils.sendGAEvent(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);
    jobject arg2 = (jobject) va_arg(args, jobject);
}

void stub_SocialUtils_sendGAScreen_165(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.SocialUtils.sendGAScreen(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

jboolean stub_SocialUtils_isAgsInitialized_166(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.SocialUtils.isAgsInitialized()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

jobject stub_SocialUtils_getTracker_167(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.tatem.iceage.utils.SocialUtils.getTracker(LTrackerName;)LTracker; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

// ---- org.fmod.FMODAudioDevice ----
void stub_FMODAudioDevice_start_168(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] org.fmod.FMODAudioDevice.start()V called -- fill in from the real Java impl (jadx).");
}

void stub_FMODAudioDevice_stop_169(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] org.fmod.FMODAudioDevice.stop()V called -- fill in from the real Java impl (jadx).");
}

void stub_FMODAudioDevice_run_170(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] org.fmod.FMODAudioDevice.run()V called -- fill in from the real Java impl (jadx).");
}

void stub_FMODAudioDevice_shutDown_171(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] org.fmod.FMODAudioDevice.shutDown()V called -- fill in from the real Java impl (jadx).");
}

