/* Auto-generated by psvita-toolkit from decompiled/apk_jadx/sources -- FalsoJNI callback candidates. */
/* Every entry here is a CANDIDATE: confirm the method belongs on the .so's actual call path, and */
/* read the real Java implementation (jadx) before trusting the stub body. See docs/dev-notes/jni_analyzer.md. */
#pragma once
#include <stdarg.h>
#include <falso_jni/FalsoJNI_Impl.h>

extern void stub_AGSJniHandler_initializeJni_0(jmethodID id, va_list args);
extern void stub_AGSJniHandler_loadLibrary_1(jmethodID id, va_list args);
extern jboolean stub_AGSJniHandler_isLibraryLoaded_2(jmethodID id, va_list args);
extern jobject stub_NaCl_a_3(jmethodID id, va_list args);
extern jboolean stub_CrittercismNDK_installLib_4(jmethodID id, va_list args);
extern void stub_CrittercismNDK_installNdkLib_5(jmethodID id, va_list args);
extern jobject stub_Billing_Billing_6(jmethodID id, va_list args);
extern void stub_Billing_addObserver_7(jmethodID id, va_list args);
extern void stub_Billing_removeObserver_8(jmethodID id, va_list args);
extern void stub_Billing_destroy_9(jmethodID id, va_list args);
extern void stub_Billing_onActivityResult_10(jmethodID id, va_list args);
extern void stub_Billing_notifyItemPurhcased_11(jmethodID id, va_list args);
extern void stub_Billing_notifyPurchaseRestored_12(jmethodID id, va_list args);
extern void stub_Billing_notifyPurchaseCanceled_13(jmethodID id, va_list args);
extern void stub_Billing_notifyPurchaseFailed_14(jmethodID id, va_list args);
extern void stub_Billing_log_15(jmethodID id, va_list args);
extern jobject stub_IceAgeAndroid_getInstance_16(jmethodID id, va_list args);
extern jobject stub_IceAgeAndroid_getGameHelper_17(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_onCreate_18(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_onStart_19(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_onStop_20(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_onActivityResult_21(jmethodID id, va_list args);
extern jobject stub_IceAgeAndroid_getApiClient_22(jmethodID id, va_list args);
extern jboolean stub_IceAgeAndroid_isSignedIn_23(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_beginUserInitiatedSignIn_24(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_beginUserInitiatedSignIn_25(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_signOut_26(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_showAlert_27(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_showAlert_28(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_enableDebugLog_29(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_enableDebugLog_30(jmethodID id, va_list args);
extern jobject stub_IceAgeAndroid_getInvitationId_31(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_reconnectClient_32(jmethodID id, va_list args);
extern jboolean stub_IceAgeAndroid_hasSignInError_33(jmethodID id, va_list args);
extern jobject stub_IceAgeAndroid_getSignInError_34(jmethodID id, va_list args);
extern jobject stub_IceAgeAndroid_getSignInTextError_35(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_onWindowFocusChanged_36(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_finish_37(jmethodID id, va_list args);
extern jboolean stub_IceAgeAndroid_onKeyDown_38(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_onBackPressed_39(jmethodID id, va_list args);
extern jobject stub_IceAgeAndroid_onCreateDialog_40(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_postDownloadInit_41(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_checkBundles_42(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_continueCreating_43(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_loadThanksGivingMode_44(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_createGallery_45(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_createSocialButton_46(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_createHotAppButton_47(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_showLoadingDialog_48(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_hideLoadingDialog_49(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_showAlertDialog_50(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_showSplash_51(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_onLoadingCompleted_52(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_init_53(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_initViews_54(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_setActivityOptions_55(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_onPause_56(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_onResume_57(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_onDestroy_58(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_showGallery_59(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_hideGallery_60(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_createHelpView_61(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_showTutorial_62(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_hideTutorial_63(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_showInAppInfo_64(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_hideInAppInfo_65(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_setTutorialFile_66(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_putFrameOnPhoto_67(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_showSignInDialog_68(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_showSignInProposeAtFirst_69(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_showSignInPropose_70(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_showSignInPropose_71(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_showSocialButton_72(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_hideSocialButton_73(jmethodID id, va_list args);
extern jobject stub_IceAgeAndroid_getCurrentLanguage_74(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_checkLanguageChange_75(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_showSpinner_76(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_hideSpinner_77(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_isInGameMode_78(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_isInMenuMode_79(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_createInAppInfoView_80(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_processPurchaseForGoogle_81(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_initAmazonBilling_82(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_processPurchase_83(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_purchaseItem_84(jmethodID id, va_list args);
extern jobject stub_IceAgeAndroid_processSnapshotOpenResult_85(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_resolveSnapshotConflict_86(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_saveSnapshot_87(jmethodID id, va_list args);
extern jobject stub_IceAgeAndroid_writeSnapshot_88(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_loadFromSnapshot_89(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_setLoadingBalance_90(jmethodID id, va_list args);
extern jobject stub_IceAgeAndroid_getSnapshot_91(jmethodID id, va_list args);
extern void stub_IceAgeAndroid_setSnapshot_92(jmethodID id, va_list args);
extern jobject stub_IceAgeGLSurface_IceAgeGLSurface_93(jmethodID id, va_list args);
extern jobject stub_IceAgeGLSurface_IceAgeGLSurface_94(jmethodID id, va_list args);
extern jboolean stub_IceAgeGLSurface_onTouchEvent_95(jmethodID id, va_list args);
extern void stub_IceAgeGLSurface_dumpEvent_96(jmethodID id, va_list args);
extern jobject stub_IceAgeRenderer_IceAgeRenderer_97(jmethodID id, va_list args);
extern void stub_IceAgeRenderer_onDrawFrame_98(jmethodID id, va_list args);
extern void stub_IceAgeRenderer_onSurfaceChanged_99(jmethodID id, va_list args);
extern void stub_IceAgeRenderer_onSurfaceCreated_100(jmethodID id, va_list args);
extern jobject stub_FacebookWrapper_FacebookWrapper_101(jmethodID id, va_list args);
extern void stub_FacebookWrapper_onStart_102(jmethodID id, va_list args);
extern void stub_FacebookWrapper_onStop_103(jmethodID id, va_list args);
extern void stub_FacebookWrapper_logIn_104(jmethodID id, va_list args);
extern void stub_FacebookWrapper_logOut_105(jmethodID id, va_list args);
extern jboolean stub_FacebookWrapper_isLoggedIn_106(jmethodID id, va_list args);
extern void stub_FacebookWrapper_publishFeed_107(jmethodID id, va_list args);
extern void stub_FacebookWrapper_getUserName_108(jmethodID id, va_list args);
extern void stub_FacebookWrapper_onClickLogin_109(jmethodID id, va_list args);
extern void stub_FacebookWrapper_onClickLogout_110(jmethodID id, va_list args);
extern void stub_FacebookWrapper_showDialogWithoutNotificationBar_111(jmethodID id, va_list args);
extern jobject stub_FyberManager_FyberManager_112(jmethodID id, va_list args);
extern void stub_FyberManager_startFyber_113(jmethodID id, va_list args);
extern jobject stub_FyberManager_getButtonText_114(jmethodID id, va_list args);
extern void stub_FyberManager_showAd_115(jmethodID id, va_list args);
extern void stub_FyberManager_isFyberAdsAvaliable_116(jmethodID id, va_list args);
extern void stub_FyberManager_isReviveAvailable_117(jmethodID id, va_list args);
extern void stub_FyberManager_onActivityResult_118(jmethodID id, va_list args);
extern jobject stub_InternetUtils_InternetUtils_119(jmethodID id, va_list args);
extern void stub_InternetUtils_onConnectSuccess_120(jmethodID id, va_list args);
extern void stub_InternetUtils_onConnectFails_121(jmethodID id, va_list args);
extern jobject stub_InternetUtils_getInstance_122(jmethodID id, va_list args);
extern void stub_InternetUtils_onPause_123(jmethodID id, va_list args);
extern void stub_InternetUtils_onResume_124(jmethodID id, va_list args);
extern void stub_InternetUtils_onDestroy_125(jmethodID id, va_list args);
extern jboolean stub_InternetUtils_isOnline_126(jmethodID id, va_list args);
extern void stub_InternetUtils_showOfflineDialog_127(jmethodID id, va_list args);
extern void stub_InternetUtils_openHotAppBanner_128(jmethodID id, va_list args);
extern jboolean stub_InternetUtils_getOfferwalShowed_129(jmethodID id, va_list args);
extern void stub_InternetUtils_setOfferWallShowed_130(jmethodID id, va_list args);
extern void stub_InternetUtils_openAfterGameStarts_131(jmethodID id, va_list args);
extern void stub_InternetUtils_openMoreGames_132(jmethodID id, va_list args);
extern void stub_InternetUtils_openTapJoyOffers_133(jmethodID id, va_list args);
extern void stub_InternetUtils_openMarketAtPackage_134(jmethodID id, va_list args);
extern void stub_InternetUtils_LoadAd_135(jmethodID id, va_list args);
extern void stub_InternetUtils_createAMZNAd_136(jmethodID id, va_list args);
extern void stub_InternetUtils_removeAMZNAd_137(jmethodID id, va_list args);
extern void stub_InternetUtils_showAMZNAd_138(jmethodID id, va_list args);
extern void stub_InternetUtils_onAdCollapsed_139(jmethodID id, va_list args);
extern void stub_InternetUtils_onAdFailedToLoad_140(jmethodID id, va_list args);
extern void stub_InternetUtils_onAdLoaded_141(jmethodID id, va_list args);
extern void stub_InternetUtils_onAdExpanded_142(jmethodID id, va_list args);
extern void stub_InternetUtils_downloadPromoteJSON_143(jmethodID id, va_list args);
extern jobject stub_InternetUtils_HTTPGetCall_144(jmethodID id, va_list args);
extern jobject stub_MoPubManager_MoPubManager_145(jmethodID id, va_list args);
extern void stub_MoPubManager_onCreate_146(jmethodID id, va_list args);
extern void stub_MoPubManager_onDestroy_147(jmethodID id, va_list args);
extern void stub_MoPubManager_showAd_148(jmethodID id, va_list args);
extern jobject stub_MoPubManager_getNeedfulId_149(jmethodID id, va_list args);
extern jobject stub_SocialUtils_SocialUtils_150(jmethodID id, va_list args);
extern jobject stub_SocialUtils_getInstance_151(jmethodID id, va_list args);
extern void stub_SocialUtils_onResume_152(jmethodID id, va_list args);
extern void stub_SocialUtils_onPause_153(jmethodID id, va_list args);
extern void stub_SocialUtils_initAchievements_154(jmethodID id, va_list args);
extern void stub_SocialUtils_synchronizeGameData_155(jmethodID id, va_list args);
extern void stub_SocialUtils_syncProgress_156(jmethodID id, va_list args);
extern void stub_SocialUtils_initSocial_157(jmethodID id, va_list args);
extern void stub_SocialUtils_setAchievementsIDs_158(jmethodID id, va_list args);
extern void stub_SocialUtils_openAchievements_159(jmethodID id, va_list args);
extern void stub_SocialUtils_openDashboard_160(jmethodID id, va_list args);
extern void stub_SocialUtils_unlockAchievement_161(jmethodID id, va_list args);
extern void stub_SocialUtils_SendFlurryEvent_162(jmethodID id, va_list args);
extern void stub_SocialUtils_sendGAEvent_163(jmethodID id, va_list args);
extern void stub_SocialUtils_sendGAEvent_164(jmethodID id, va_list args);
extern void stub_SocialUtils_sendGAScreen_165(jmethodID id, va_list args);
extern jboolean stub_SocialUtils_isAgsInitialized_166(jmethodID id, va_list args);
extern jobject stub_SocialUtils_getTracker_167(jmethodID id, va_list args);
extern void stub_FMODAudioDevice_start_168(jmethodID id, va_list args);
extern void stub_FMODAudioDevice_stop_169(jmethodID id, va_list args);
extern void stub_FMODAudioDevice_run_170(jmethodID id, va_list args);
extern void stub_FMODAudioDevice_shutDown_171(jmethodID id, va_list args);

// Candidate NameToMethodID entries -- append into the real nameToMethodId[] in java.c
static const NameToMethodID generated_nameToMethodId[] = {
    { 0, "initializeJni", METHOD_TYPE_VOID },  // com.amazon.ags.jni.AGSJniHandler
    { 1, "loadLibrary", METHOD_TYPE_VOID },  // com.amazon.ags.jni.AGSJniHandler
    { 2, "isLibraryLoaded", METHOD_TYPE_BOOLEAN },  // com.amazon.ags.jni.AGSJniHandler
    { 3, "a", METHOD_TYPE_OBJECT },  // com.chartboost.sdk.Libraries.NaCl
    { 4, "installLib", METHOD_TYPE_BOOLEAN },  // com.crittercism.app.CrittercismNDK
    { 5, "installNdkLib", METHOD_TYPE_VOID },  // com.crittercism.app.CrittercismNDK
    { 6, "Billing", METHOD_TYPE_OBJECT },  // com.tatem.billing.Billing
    { 7, "addObserver", METHOD_TYPE_VOID },  // com.tatem.billing.Billing
    { 8, "removeObserver", METHOD_TYPE_VOID },  // com.tatem.billing.Billing
    { 9, "destroy", METHOD_TYPE_VOID },  // com.tatem.billing.Billing
    { 10, "onActivityResult", METHOD_TYPE_VOID },  // com.tatem.billing.Billing
    { 11, "notifyItemPurhcased", METHOD_TYPE_VOID },  // com.tatem.billing.Billing
    { 12, "notifyPurchaseRestored", METHOD_TYPE_VOID },  // com.tatem.billing.Billing
    { 13, "notifyPurchaseCanceled", METHOD_TYPE_VOID },  // com.tatem.billing.Billing
    { 14, "notifyPurchaseFailed", METHOD_TYPE_VOID },  // com.tatem.billing.Billing
    { 15, "log", METHOD_TYPE_VOID },  // com.tatem.billing.Billing
    { 16, "getInstance", METHOD_TYPE_OBJECT },  // com.tatem.iceage.IceAgeAndroid
    { 17, "getGameHelper", METHOD_TYPE_OBJECT },  // com.tatem.iceage.IceAgeAndroid
    { 18, "onCreate", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 19, "onStart", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 20, "onStop", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 21, "onActivityResult", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 22, "getApiClient", METHOD_TYPE_OBJECT },  // com.tatem.iceage.IceAgeAndroid
    { 23, "isSignedIn", METHOD_TYPE_BOOLEAN },  // com.tatem.iceage.IceAgeAndroid
    { 24, "beginUserInitiatedSignIn", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 25, "beginUserInitiatedSignIn", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 26, "signOut", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 27, "showAlert", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 28, "showAlert", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 29, "enableDebugLog", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 30, "enableDebugLog", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 31, "getInvitationId", METHOD_TYPE_OBJECT },  // com.tatem.iceage.IceAgeAndroid
    { 32, "reconnectClient", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 33, "hasSignInError", METHOD_TYPE_BOOLEAN },  // com.tatem.iceage.IceAgeAndroid
    { 34, "getSignInError", METHOD_TYPE_OBJECT },  // com.tatem.iceage.IceAgeAndroid
    { 35, "getSignInTextError", METHOD_TYPE_OBJECT },  // com.tatem.iceage.IceAgeAndroid
    { 36, "onWindowFocusChanged", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 37, "finish", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 38, "onKeyDown", METHOD_TYPE_BOOLEAN },  // com.tatem.iceage.IceAgeAndroid
    { 39, "onBackPressed", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 40, "onCreateDialog", METHOD_TYPE_OBJECT },  // com.tatem.iceage.IceAgeAndroid
    { 41, "postDownloadInit", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 42, "checkBundles", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 43, "continueCreating", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 44, "loadThanksGivingMode", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 45, "createGallery", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 46, "createSocialButton", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 47, "createHotAppButton", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 48, "showLoadingDialog", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 49, "hideLoadingDialog", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 50, "showAlertDialog", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 51, "showSplash", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 52, "onLoadingCompleted", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 53, "init", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 54, "initViews", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 55, "setActivityOptions", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 56, "onPause", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 57, "onResume", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 58, "onDestroy", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 59, "showGallery", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 60, "hideGallery", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 61, "createHelpView", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 62, "showTutorial", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 63, "hideTutorial", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 64, "showInAppInfo", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 65, "hideInAppInfo", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 66, "setTutorialFile", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 67, "putFrameOnPhoto", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 68, "showSignInDialog", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 69, "showSignInProposeAtFirst", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 70, "showSignInPropose", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 71, "showSignInPropose", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 72, "showSocialButton", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 73, "hideSocialButton", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 74, "getCurrentLanguage", METHOD_TYPE_OBJECT },  // com.tatem.iceage.IceAgeAndroid
    { 75, "checkLanguageChange", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 76, "showSpinner", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 77, "hideSpinner", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 78, "isInGameMode", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 79, "isInMenuMode", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 80, "createInAppInfoView", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 81, "processPurchaseForGoogle", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 82, "initAmazonBilling", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 83, "processPurchase", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 84, "purchaseItem", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 85, "processSnapshotOpenResult", METHOD_TYPE_OBJECT },  // com.tatem.iceage.IceAgeAndroid
    { 86, "resolveSnapshotConflict", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 87, "saveSnapshot", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 88, "writeSnapshot", METHOD_TYPE_OBJECT },  // com.tatem.iceage.IceAgeAndroid
    { 89, "loadFromSnapshot", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 90, "setLoadingBalance", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 91, "getSnapshot", METHOD_TYPE_OBJECT },  // com.tatem.iceage.IceAgeAndroid
    { 92, "setSnapshot", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeAndroid
    { 93, "IceAgeGLSurface", METHOD_TYPE_OBJECT },  // com.tatem.iceage.IceAgeGLSurface
    { 94, "IceAgeGLSurface", METHOD_TYPE_OBJECT },  // com.tatem.iceage.IceAgeGLSurface
    { 95, "onTouchEvent", METHOD_TYPE_BOOLEAN },  // com.tatem.iceage.IceAgeGLSurface
    { 96, "dumpEvent", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeGLSurface
    { 97, "IceAgeRenderer", METHOD_TYPE_OBJECT },  // com.tatem.iceage.IceAgeRenderer
    { 98, "onDrawFrame", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeRenderer
    { 99, "onSurfaceChanged", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeRenderer
    { 100, "onSurfaceCreated", METHOD_TYPE_VOID },  // com.tatem.iceage.IceAgeRenderer
    { 101, "FacebookWrapper", METHOD_TYPE_OBJECT },  // com.tatem.iceage.utils.FacebookWrapper
    { 102, "onStart", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.FacebookWrapper
    { 103, "onStop", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.FacebookWrapper
    { 104, "logIn", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.FacebookWrapper
    { 105, "logOut", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.FacebookWrapper
    { 106, "isLoggedIn", METHOD_TYPE_BOOLEAN },  // com.tatem.iceage.utils.FacebookWrapper
    { 107, "publishFeed", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.FacebookWrapper
    { 108, "getUserName", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.FacebookWrapper
    { 109, "onClickLogin", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.FacebookWrapper
    { 110, "onClickLogout", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.FacebookWrapper
    { 111, "showDialogWithoutNotificationBar", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.FacebookWrapper
    { 112, "FyberManager", METHOD_TYPE_OBJECT },  // com.tatem.iceage.utils.FyberManager
    { 113, "startFyber", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.FyberManager
    { 114, "getButtonText", METHOD_TYPE_OBJECT },  // com.tatem.iceage.utils.FyberManager
    { 115, "showAd", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.FyberManager
    { 116, "isFyberAdsAvaliable", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.FyberManager
    { 117, "isReviveAvailable", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.FyberManager
    { 118, "onActivityResult", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.FyberManager
    { 119, "InternetUtils", METHOD_TYPE_OBJECT },  // com.tatem.iceage.utils.InternetUtils
    { 120, "onConnectSuccess", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 121, "onConnectFails", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 122, "getInstance", METHOD_TYPE_OBJECT },  // com.tatem.iceage.utils.InternetUtils
    { 123, "onPause", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 124, "onResume", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 125, "onDestroy", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 126, "isOnline", METHOD_TYPE_BOOLEAN },  // com.tatem.iceage.utils.InternetUtils
    { 127, "showOfflineDialog", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 128, "openHotAppBanner", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 129, "getOfferwalShowed", METHOD_TYPE_BOOLEAN },  // com.tatem.iceage.utils.InternetUtils
    { 130, "setOfferWallShowed", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 131, "openAfterGameStarts", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 132, "openMoreGames", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 133, "openTapJoyOffers", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 134, "openMarketAtPackage", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 135, "LoadAd", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 136, "createAMZNAd", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 137, "removeAMZNAd", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 138, "showAMZNAd", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 139, "onAdCollapsed", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 140, "onAdFailedToLoad", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 141, "onAdLoaded", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 142, "onAdExpanded", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 143, "downloadPromoteJSON", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.InternetUtils
    { 144, "HTTPGetCall", METHOD_TYPE_OBJECT },  // com.tatem.iceage.utils.InternetUtils
    { 145, "MoPubManager", METHOD_TYPE_OBJECT },  // com.tatem.iceage.utils.MoPubManager
    { 146, "onCreate", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.MoPubManager
    { 147, "onDestroy", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.MoPubManager
    { 148, "showAd", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.MoPubManager
    { 149, "getNeedfulId", METHOD_TYPE_OBJECT },  // com.tatem.iceage.utils.MoPubManager
    { 150, "SocialUtils", METHOD_TYPE_OBJECT },  // com.tatem.iceage.utils.SocialUtils
    { 151, "getInstance", METHOD_TYPE_OBJECT },  // com.tatem.iceage.utils.SocialUtils
    { 152, "onResume", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.SocialUtils
    { 153, "onPause", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.SocialUtils
    { 154, "initAchievements", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.SocialUtils
    { 155, "synchronizeGameData", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.SocialUtils
    { 156, "syncProgress", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.SocialUtils
    { 157, "initSocial", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.SocialUtils
    { 158, "setAchievementsIDs", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.SocialUtils
    { 159, "openAchievements", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.SocialUtils
    { 160, "openDashboard", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.SocialUtils
    { 161, "unlockAchievement", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.SocialUtils
    { 162, "SendFlurryEvent", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.SocialUtils
    { 163, "sendGAEvent", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.SocialUtils
    { 164, "sendGAEvent", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.SocialUtils
    { 165, "sendGAScreen", METHOD_TYPE_VOID },  // com.tatem.iceage.utils.SocialUtils
    { 166, "isAgsInitialized", METHOD_TYPE_BOOLEAN },  // com.tatem.iceage.utils.SocialUtils
    { 167, "getTracker", METHOD_TYPE_OBJECT },  // com.tatem.iceage.utils.SocialUtils
    { 168, "start", METHOD_TYPE_VOID },  // org.fmod.FMODAudioDevice
    { 169, "stop", METHOD_TYPE_VOID },  // org.fmod.FMODAudioDevice
    { 170, "run", METHOD_TYPE_VOID },  // org.fmod.FMODAudioDevice
    { 171, "shutDown", METHOD_TYPE_VOID },  // org.fmod.FMODAudioDevice
};

// Candidate methodsVoid[] entries -- append into the real methodsVoid[] in java.c
static const MethodsVoid generated_methodsVoid[] = {
    { 0, stub_AGSJniHandler_initializeJni_0 },
    { 1, stub_AGSJniHandler_loadLibrary_1 },
    { 5, stub_CrittercismNDK_installNdkLib_5 },
    { 7, stub_Billing_addObserver_7 },
    { 8, stub_Billing_removeObserver_8 },
    { 9, stub_Billing_destroy_9 },
    { 10, stub_Billing_onActivityResult_10 },
    { 11, stub_Billing_notifyItemPurhcased_11 },
    { 12, stub_Billing_notifyPurchaseRestored_12 },
    { 13, stub_Billing_notifyPurchaseCanceled_13 },
    { 14, stub_Billing_notifyPurchaseFailed_14 },
    { 15, stub_Billing_log_15 },
    { 18, stub_IceAgeAndroid_onCreate_18 },
    { 19, stub_IceAgeAndroid_onStart_19 },
    { 20, stub_IceAgeAndroid_onStop_20 },
    { 21, stub_IceAgeAndroid_onActivityResult_21 },
    { 24, stub_IceAgeAndroid_beginUserInitiatedSignIn_24 },
    { 25, stub_IceAgeAndroid_beginUserInitiatedSignIn_25 },
    { 26, stub_IceAgeAndroid_signOut_26 },
    { 27, stub_IceAgeAndroid_showAlert_27 },
    { 28, stub_IceAgeAndroid_showAlert_28 },
    { 29, stub_IceAgeAndroid_enableDebugLog_29 },
    { 30, stub_IceAgeAndroid_enableDebugLog_30 },
    { 32, stub_IceAgeAndroid_reconnectClient_32 },
    { 36, stub_IceAgeAndroid_onWindowFocusChanged_36 },
    { 37, stub_IceAgeAndroid_finish_37 },
    { 39, stub_IceAgeAndroid_onBackPressed_39 },
    { 41, stub_IceAgeAndroid_postDownloadInit_41 },
    { 42, stub_IceAgeAndroid_checkBundles_42 },
    { 43, stub_IceAgeAndroid_continueCreating_43 },
    { 44, stub_IceAgeAndroid_loadThanksGivingMode_44 },
    { 45, stub_IceAgeAndroid_createGallery_45 },
    { 46, stub_IceAgeAndroid_createSocialButton_46 },
    { 47, stub_IceAgeAndroid_createHotAppButton_47 },
    { 48, stub_IceAgeAndroid_showLoadingDialog_48 },
    { 49, stub_IceAgeAndroid_hideLoadingDialog_49 },
    { 50, stub_IceAgeAndroid_showAlertDialog_50 },
    { 51, stub_IceAgeAndroid_showSplash_51 },
    { 52, stub_IceAgeAndroid_onLoadingCompleted_52 },
    { 53, stub_IceAgeAndroid_init_53 },
    { 54, stub_IceAgeAndroid_initViews_54 },
    { 55, stub_IceAgeAndroid_setActivityOptions_55 },
    { 56, stub_IceAgeAndroid_onPause_56 },
    { 57, stub_IceAgeAndroid_onResume_57 },
    { 58, stub_IceAgeAndroid_onDestroy_58 },
    { 59, stub_IceAgeAndroid_showGallery_59 },
    { 60, stub_IceAgeAndroid_hideGallery_60 },
    { 61, stub_IceAgeAndroid_createHelpView_61 },
    { 62, stub_IceAgeAndroid_showTutorial_62 },
    { 63, stub_IceAgeAndroid_hideTutorial_63 },
    { 64, stub_IceAgeAndroid_showInAppInfo_64 },
    { 65, stub_IceAgeAndroid_hideInAppInfo_65 },
    { 66, stub_IceAgeAndroid_setTutorialFile_66 },
    { 67, stub_IceAgeAndroid_putFrameOnPhoto_67 },
    { 68, stub_IceAgeAndroid_showSignInDialog_68 },
    { 69, stub_IceAgeAndroid_showSignInProposeAtFirst_69 },
    { 70, stub_IceAgeAndroid_showSignInPropose_70 },
    { 71, stub_IceAgeAndroid_showSignInPropose_71 },
    { 72, stub_IceAgeAndroid_showSocialButton_72 },
    { 73, stub_IceAgeAndroid_hideSocialButton_73 },
    { 75, stub_IceAgeAndroid_checkLanguageChange_75 },
    { 76, stub_IceAgeAndroid_showSpinner_76 },
    { 77, stub_IceAgeAndroid_hideSpinner_77 },
    { 78, stub_IceAgeAndroid_isInGameMode_78 },
    { 79, stub_IceAgeAndroid_isInMenuMode_79 },
    { 80, stub_IceAgeAndroid_createInAppInfoView_80 },
    { 81, stub_IceAgeAndroid_processPurchaseForGoogle_81 },
    { 82, stub_IceAgeAndroid_initAmazonBilling_82 },
    { 83, stub_IceAgeAndroid_processPurchase_83 },
    { 84, stub_IceAgeAndroid_purchaseItem_84 },
    { 86, stub_IceAgeAndroid_resolveSnapshotConflict_86 },
    { 87, stub_IceAgeAndroid_saveSnapshot_87 },
    { 89, stub_IceAgeAndroid_loadFromSnapshot_89 },
    { 90, stub_IceAgeAndroid_setLoadingBalance_90 },
    { 92, stub_IceAgeAndroid_setSnapshot_92 },
    { 96, stub_IceAgeGLSurface_dumpEvent_96 },
    { 98, stub_IceAgeRenderer_onDrawFrame_98 },
    { 99, stub_IceAgeRenderer_onSurfaceChanged_99 },
    { 100, stub_IceAgeRenderer_onSurfaceCreated_100 },
    { 102, stub_FacebookWrapper_onStart_102 },
    { 103, stub_FacebookWrapper_onStop_103 },
    { 104, stub_FacebookWrapper_logIn_104 },
    { 105, stub_FacebookWrapper_logOut_105 },
    { 107, stub_FacebookWrapper_publishFeed_107 },
    { 108, stub_FacebookWrapper_getUserName_108 },
    { 109, stub_FacebookWrapper_onClickLogin_109 },
    { 110, stub_FacebookWrapper_onClickLogout_110 },
    { 111, stub_FacebookWrapper_showDialogWithoutNotificationBar_111 },
    { 113, stub_FyberManager_startFyber_113 },
    { 115, stub_FyberManager_showAd_115 },
    { 116, stub_FyberManager_isFyberAdsAvaliable_116 },
    { 117, stub_FyberManager_isReviveAvailable_117 },
    { 118, stub_FyberManager_onActivityResult_118 },
    { 120, stub_InternetUtils_onConnectSuccess_120 },
    { 121, stub_InternetUtils_onConnectFails_121 },
    { 123, stub_InternetUtils_onPause_123 },
    { 124, stub_InternetUtils_onResume_124 },
    { 125, stub_InternetUtils_onDestroy_125 },
    { 127, stub_InternetUtils_showOfflineDialog_127 },
    { 128, stub_InternetUtils_openHotAppBanner_128 },
    { 130, stub_InternetUtils_setOfferWallShowed_130 },
    { 131, stub_InternetUtils_openAfterGameStarts_131 },
    { 132, stub_InternetUtils_openMoreGames_132 },
    { 133, stub_InternetUtils_openTapJoyOffers_133 },
    { 134, stub_InternetUtils_openMarketAtPackage_134 },
    { 135, stub_InternetUtils_LoadAd_135 },
    { 136, stub_InternetUtils_createAMZNAd_136 },
    { 137, stub_InternetUtils_removeAMZNAd_137 },
    { 138, stub_InternetUtils_showAMZNAd_138 },
    { 139, stub_InternetUtils_onAdCollapsed_139 },
    { 140, stub_InternetUtils_onAdFailedToLoad_140 },
    { 141, stub_InternetUtils_onAdLoaded_141 },
    { 142, stub_InternetUtils_onAdExpanded_142 },
    { 143, stub_InternetUtils_downloadPromoteJSON_143 },
    { 146, stub_MoPubManager_onCreate_146 },
    { 147, stub_MoPubManager_onDestroy_147 },
    { 148, stub_MoPubManager_showAd_148 },
    { 152, stub_SocialUtils_onResume_152 },
    { 153, stub_SocialUtils_onPause_153 },
    { 154, stub_SocialUtils_initAchievements_154 },
    { 155, stub_SocialUtils_synchronizeGameData_155 },
    { 156, stub_SocialUtils_syncProgress_156 },
    { 157, stub_SocialUtils_initSocial_157 },
    { 158, stub_SocialUtils_setAchievementsIDs_158 },
    { 159, stub_SocialUtils_openAchievements_159 },
    { 160, stub_SocialUtils_openDashboard_160 },
    { 161, stub_SocialUtils_unlockAchievement_161 },
    { 162, stub_SocialUtils_SendFlurryEvent_162 },
    { 163, stub_SocialUtils_sendGAEvent_163 },
    { 164, stub_SocialUtils_sendGAEvent_164 },
    { 165, stub_SocialUtils_sendGAScreen_165 },
    { 168, stub_FMODAudioDevice_start_168 },
    { 169, stub_FMODAudioDevice_stop_169 },
    { 170, stub_FMODAudioDevice_run_170 },
    { 171, stub_FMODAudioDevice_shutDown_171 },
};

// Candidate methodsBoolean[] entries -- append into the real methodsBoolean[] in java.c
static const MethodsBoolean generated_methodsBoolean[] = {
    { 2, stub_AGSJniHandler_isLibraryLoaded_2 },
    { 4, stub_CrittercismNDK_installLib_4 },
    { 23, stub_IceAgeAndroid_isSignedIn_23 },
    { 33, stub_IceAgeAndroid_hasSignInError_33 },
    { 38, stub_IceAgeAndroid_onKeyDown_38 },
    { 95, stub_IceAgeGLSurface_onTouchEvent_95 },
    { 106, stub_FacebookWrapper_isLoggedIn_106 },
    { 126, stub_InternetUtils_isOnline_126 },
    { 129, stub_InternetUtils_getOfferwalShowed_129 },
    { 166, stub_SocialUtils_isAgsInitialized_166 },
};

// Candidate methodsObject[] entries -- append into the real methodsObject[] in java.c
static const MethodsObject generated_methodsObject[] = {
    { 3, stub_NaCl_a_3 },
    { 6, stub_Billing_Billing_6 },
    { 16, stub_IceAgeAndroid_getInstance_16 },
    { 17, stub_IceAgeAndroid_getGameHelper_17 },
    { 22, stub_IceAgeAndroid_getApiClient_22 },
    { 31, stub_IceAgeAndroid_getInvitationId_31 },
    { 34, stub_IceAgeAndroid_getSignInError_34 },
    { 35, stub_IceAgeAndroid_getSignInTextError_35 },
    { 40, stub_IceAgeAndroid_onCreateDialog_40 },
    { 74, stub_IceAgeAndroid_getCurrentLanguage_74 },
    { 85, stub_IceAgeAndroid_processSnapshotOpenResult_85 },
    { 88, stub_IceAgeAndroid_writeSnapshot_88 },
    { 91, stub_IceAgeAndroid_getSnapshot_91 },
    { 93, stub_IceAgeGLSurface_IceAgeGLSurface_93 },
    { 94, stub_IceAgeGLSurface_IceAgeGLSurface_94 },
    { 97, stub_IceAgeRenderer_IceAgeRenderer_97 },
    { 101, stub_FacebookWrapper_FacebookWrapper_101 },
    { 112, stub_FyberManager_FyberManager_112 },
    { 114, stub_FyberManager_getButtonText_114 },
    { 119, stub_InternetUtils_InternetUtils_119 },
    { 122, stub_InternetUtils_getInstance_122 },
    { 144, stub_InternetUtils_HTTPGetCall_144 },
    { 145, stub_MoPubManager_MoPubManager_145 },
    { 149, stub_MoPubManager_getNeedfulId_149 },
    { 150, stub_SocialUtils_SocialUtils_150 },
    { 151, stub_SocialUtils_getInstance_151 },
    { 167, stub_SocialUtils_getTracker_167 },
};

